<a href="https://colab.research.google.com/github/nevilshah444/Tensor_Operations/blob/main/CMPE258Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 2b: Performing tensor operations using pytorch

In [3]:
import torch
import numpy as np 
x = torch.ones(5) 
x

tensor([1., 1., 1., 1., 1.])

In [4]:
data = [[1, 0], [1, 0]]
x_data = torch.tensor(data)

In [9]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Tensor containing all ones: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Tensor containing random numbers: \n {x_rand} \n")

Tensor containing all ones: 
 tensor([[1, 1],
        [1, 1]]) 

Tensor containing random numbers: 
 tensor([[0.1729, 0.1469],
        [0.7548, 0.3502]]) 



In [8]:
# we will approach some operations descriing a tensor
tensor = torch.rand(3, 4)

print(f"Shape : {tensor.shape}")
print(f"Datatype : {tensor.dtype}")
print(f"Device : {tensor.device}")

Shape : torch.Size([3, 4])
Datatype : torch.float32
Device : cpu


In [11]:
# Perform element-wise product

tensor1 = torch.ones(4, 4)
tensor1[:,1] = 0

t1 = torch.cat([tensor1, tensor1, tensor1], dim=1)

print(f"Element wise multiplication is given as  \n {tensor1 * tensor1}")

Element wise multiplication is given as  
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
#adding a constant to every element

tensor1.add_(10)
print(tensor1)

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


In [13]:
point = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second = point[2]

second.size()


torch.Size([2])

In [14]:
point.stride()

(2, 1)

In [16]:
#Transposition

x = torch.ones(3, 2)
trans = a.transpose(0, 1)

x.shape, trans.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [18]:
#indexing & Slicing

x = list(range(6))
x[:]    
x[1:4]  
x[1:]   
x[:4]   
x[:-1]  
x[1:4:2]

[1, 3]