<a href="https://colab.research.google.com/github/nevilshah444/Tensor_Operations/blob/main/CMPE258_Assignment2_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 1 : Performing basic operations on tensor

A tensor is basically a container that is used to store the numerical data and it is a basic data structure used in Machine Learning Algorithms.

In this assignment, we will perform some basic operations on tensor

In [ ]:
import tensorflow as tf
import numpy as np

# Scalar Tensor

In [ ]:
# It is just a data structure storing constants and the rank is zero.
scalar_tensor = tf.constant(1)
print(scalar_tensor)

tf.Tensor(1, shape=(), dtype=int32)


#Vector Tensor (Rank 1 tensor)

In [ ]:
# Rank 1 tensor
vector_tensor = tf.constant([1.0, 2.0, 3.0, 4.0])
print(vector_tensor)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


#Matrix Tensor

In this section, we will not only define the matrix tensors, but also perform some of the arithmetic operations over them.

In [ ]:
matrix_tensor1 =  tf.constant([[1, 1],[1, 1]]) # this will create a 2x2 matrix

matrix_tensor2 =  tf.constant([[1, 0], [0,1]])

matrix_tensor3 =  tf.constant([[1, 0], [0,1],[5,6]])



In [ ]:
#perform operations on Matrix tensors

# Largest value inside the matrix tensor
print("Largest value of tensor 1 ",tf.reduce_max(matrix_tensor1))
print("Largest value of tensor 2 ",tf.reduce_max(matrix_tensor2))
# Index of the largest value present inside the matrix tensor
print("index of Largest value of tensor 1",tf.argmax(matrix_tensor1))
print("index of Largest value of tensor 2",tf.argmax(matrix_tensor2))
# Arithmetic Addition of 2 tensors
print("Arithmetic Addition",tf.add(matrix_tensor1, matrix_tensor2), "\n")
# Multiplication of 2 tensors
print("Multiplication",tf.multiply(matrix_tensor1, matrix_tensor2), "\n")
# Matrix Multiplication
print("Matrix Multiplication",tf.matmul(matrix_tensor1, matrix_tensor2), "\n")


Largest value of tensor 1  tf.Tensor(1, shape=(), dtype=int32)
Largest value of tensor 2  tf.Tensor(1, shape=(), dtype=int32)
index of Largest value of tensor 1 tf.Tensor([0 0], shape=(2,), dtype=int64)
index of Largest value of tensor 2 tf.Tensor([0 1], shape=(2,), dtype=int64)
Arithmetic Addition tf.Tensor(
[[2 1]
 [1 2]], shape=(2, 2), dtype=int32) 

Multiplication tf.Tensor(
[[1 0]
 [0 1]], shape=(2, 2), dtype=int32) 

Matrix Multiplication tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32) 



In [ ]:
print("Type of every element:", matrix_tensor1.dtype)
print("Number of axes:", matrix_tensor1.ndim)
print("Shape of tensor:", matrix_tensor1.shape)
print("Elements along axis 0 of tensor:", matrix_tensor1.shape[0])
print("Elements along the last axis of tensor:", matrix_tensor1.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(matrix_tensor1).numpy())

Type of every element: <dtype: 'int32'>
Number of axes: 2
Shape of tensor: (2, 2)
Elements along axis 0 of tensor: 2
Elements along the last axis of tensor: 2
Total number of elements (3*2*4*5):  4


#Indexing

In [ ]:
# Scalar tensor

tensor1 = tf.zeros([1,2,3,4,5,6,7,8,9])

print("Integer present:", tensor1.ndim)

print("Shape :", tensor1.shape)

print("Elements along second axis of tensor:", tensor1.shape[2])

print("Elements along the last axis of tensor:", tensor1.shape[-1])

Integer present: 9
Shape : (1, 2, 3, 4, 5, 6, 7, 8, 9)
Elements along second axis of tensor: 3
Elements along the last axis of tensor: 9


In [ ]:
# Slicing of the indices to get a specific portion of the tensor
print("The tensor displayed is :", matrix_tensor3[:].numpy())

print("From 3, before the second last element:", matrix_tensor3[2:7].numpy())
print("Reversed tensor is displayed as :", matrix_tensor3[::-1].numpy())

The tensor displayed is : [[1 0]
 [0 1]
 [5 6]]
From 3, before the second last element: [[5 6]]
Reversed tensor is displayed as : [[5 6]
 [0 1]
 [1 0]]


Size Manipulation:

In [ ]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3],[4],[5],[6]])
print("The size of a tensor is ",x.shape)

The size of a tensor is  (6, 1)


In [ ]:
reshape = tf.reshape(x, [1, 6])
print("The size  of a reshaped tensor x is ",reshape.shape)
print("The reshaped tensor is", reshape)

The size  of a reshaped tensor x is  (1, 6)
The reshaped tensor is tf.Tensor([[1 2 3 4 5 6]], shape=(1, 6), dtype=int32)


#Broadcasting

If a size of a declared tensor is small, it can automatically be increased to fit a tensor with a much lasrger size. This is called broadcasting.

In [ ]:
x = tf.constant([1, 1, 1]) # a unit tensor 

y = tf.constant(2)

# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
# both operations will multiply all the elements by 2, here the size will be the same 

tf.Tensor([2 2 2], shape=(3,), dtype=int32)
tf.Tensor([2 2 2], shape=(3,), dtype=int32)


In [ ]:
# Now , we will try to the concept of broadcasting in 

Perform Matrix Multiplication after creating a tensor

In [ ]:
x = tf.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


Now, we will use a tensorflow functions on a dataset

In [ ]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# here, we will create a csv file using tempfile library
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as func:
  func.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [ ]:
# Transformation functions applying on csv file
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

In [ ]:
print('Elements of ds_tensors:')
for x in ds_tensors:
  print(x)

print('\nElements in ds_file:')
for x in ds_file:
  print(x)

Elements of ds_tensors:
tf.Tensor(
[[ 256  625]
 [1296   81]], shape=(2, 2), dtype=int32)
tf.Tensor([[16  1]], shape=(1, 2), dtype=int32)

Elements in ds_file:
tf.Tensor(
[[b'Line 1' b'Line 2']
 [b'Line 3' b'  ']], shape=(2, 2), dtype=string)


Einsum Operations:


In [ ]:
x = tf.random.normal(shape=[2, 3])
y = tf.random.normal(shape=[3, 5])
e = tf.einsum('ij,jk->ik', x, y)

print(e.shape)

(2, 5)


In [ ]:
x = tf.reshape(tf.range(9), [3,3])
d = tf.einsum('ii->i', x)
print(d.shape)

(3,)


This concludes the first portion of the assignment of performing basic operations on tensors.